config = {"DATABASE_NAME": "recap_dev",
          "DATABASE_USER": "REMOVED",
          "DATABASE_PASSWORD": "REMOVED",
          "EMAIL_HOST_PASSWORD": "REMOVED",
          "BUCKET_PREFIX": "",
          "SERVER_HOSTNAME": "http://localhost/",
          "SERVER_BASEDIR": "recap/",
          "UPLOAD_AUTHKEY": "REMOVED",
          "IA_S3_UPLOAD_KEY": "REMOVED",
          "IA_COLLECTION": "usfederalcourts",
          "IA_STORAGE_URL": "http://s3.us.archive.org",
          "DJANGO_DEBUG": False,
          "DJANGO_ADMIN": ("Recap Bugs", "youremail@example.com"),
          "DJANGO_SECRET_KEY": "REMOVED",
          "DUMP_DOCKETS": False,
          "DUMP_DOCKETS_COURT_REGEX": "b-|b$",
          "MAX_NUM_DUMP_DOCKETS": "100"
}
