from datetime import date, timedelta
from uploads.opinions_downloader import run_downloader

'''
  This file iterates over the values in the starters list below. Each item in the list is
  a starter dict, which has the start date, end date and court code for each court.

  For each item in the starters variable, we grab the court code, and dates, and start
  working backwards until we hit the end.

  We omit weekends, under the assumption that federal workers relax during the weekends.
  While this assumption may occasionally be wrong, it's probably worth making anyway,
  since it means that we make 2/7 fewer queries.
'''

starters = [
    {'court': 'almd', 'start': None, 'stop': None},
    {'court': 'alnd', 'start': None, 'stop': None},
    {'court': 'alsd', 'start': None, 'stop': None},
    {'court': 'akd', 'start': None, 'stop': None},
    {'court': 'azd', 'start': None, 'stop': None},
    {'court': 'ared', 'start': None, 'stop': None},
    {'court': 'arwd', 'start': None, 'stop': None},
    {'court': 'cacd', 'start': None, 'stop': None},
    {'court': 'caed', 'start': None, 'stop': None},
    {'court': 'cand', 'start': None, 'stop': None},
    {'court': 'casd', 'start': None, 'stop': None},
    {'court': 'cod', 'start': None, 'stop': None},
    {'court': 'ctd', 'start': None, 'stop': None},
    {'court': 'ded', 'start': None, 'stop': None},
    {'court': 'dcd', 'start': None, 'stop': None},
    {'court': 'flmd', 'start': None, 'stop': None},
    {'court': 'flnd', 'start': None, 'stop': None},
    {'court': 'flsd', 'start': None, 'stop': None},
    {'court': 'gamd', 'start': None, 'stop': None},
    {'court': 'gand', 'start': None, 'stop': None},
    {'court': 'gasd', 'start': None, 'stop': None},
    {'court': 'gud', 'start': None, 'stop': None},
    {'court': 'hid', 'start': None, 'stop': None},
    {'court': 'idd', 'start': None, 'stop': None},
    {'court': 'ilcd', 'start': None, 'stop': None},
    {'court': 'ilnd', 'start': None, 'stop': None},
    {'court': 'ilsd', 'start': None, 'stop': None},
    {'court': 'innd', 'start': None, 'stop': None},
    {'court': 'insd', 'start': None, 'stop': None},
    {'court': 'iand', 'start': None, 'stop': None},
    {'court': 'iasd', 'start': None, 'stop': None},
    {'court': 'ksd', 'start': None, 'stop': None},
    {'court': 'kyed', 'start': None, 'stop': None},
    {'court': 'kywd', 'start': None, 'stop': None},
    {'court': 'laed', 'start': None, 'stop': None},
    {'court': 'lamd', 'start': None, 'stop': None},
    {'court': 'lawd', 'start': None, 'stop': None},
    {'court': 'med', 'start': None, 'stop': None},
    {'court': 'mdd', 'start': None, 'stop': None},
    {'court': 'mad', 'start': None, 'stop': None},
    {'court': 'mied', 'start': None, 'stop': None},
    {'court': 'miwd', 'start': None, 'stop': None},
    {'court': 'mnd', 'start': None, 'stop': None},
    {'court': 'msnd', 'start': None, 'stop': None},
    {'court': 'mssd', 'start': None, 'stop': None},
    {'court': 'moed', 'start': None, 'stop': None},
    {'court': 'mowd', 'start': None, 'stop': None},
    {'court': 'mtd', 'start': None, 'stop': None},
    {'court': 'ned', 'start': None, 'stop': None},
    {'court': 'nvd', 'start': None, 'stop': None},
    {'court': 'nhd', 'start': None, 'stop': None},
    {'court': 'njd', 'start': None, 'stop': None},
    {'court': 'nmd', 'start': None, 'stop': None},
    {'court': 'nyed', 'start': None, 'stop': None},
    {'court': 'nynd', 'start': None, 'stop': None},
    {'court': 'nysd', 'start': None, 'stop': None},
    {'court': 'nywd', 'start': None, 'stop': None},
    {'court': 'nced', 'start': None, 'stop': None},
    {'court': 'ncmd', 'start': None, 'stop': None},
    {'court': 'ncwd', 'start': None, 'stop': None},
    {'court': 'ndd', 'start': None, 'stop': None},
    {'court': 'nmid', 'start': None, 'stop': None},
    {'court': 'ohnd', 'start': None, 'stop': None},
    {'court': 'ohsd', 'start': None, 'stop': None},
    {'court': 'oked', 'start': None, 'stop': None},
    {'court': 'oknd', 'start': None, 'stop': None},
    {'court': 'okwd', 'start': None, 'stop': None},
    {'court': 'ord', 'start': None, 'stop': None},
    {'court': 'paed', 'start': None, 'stop': None},
    {'court': 'pamd', 'start': None, 'stop': None},
    {'court': 'pawd', 'start': None, 'stop': None},
    {'court': 'prd', 'start': None, 'stop': None},
    {'court': 'rid', 'start': None, 'stop': None},
    {'court': 'scd', 'start': None, 'stop': None},
    {'court': 'sdd', 'start': None, 'stop': None},
    {'court': 'tned', 'start': None, 'stop': None},
    {'court': 'tnmd', 'start': None, 'stop': None},
    {'court': 'tnwd', 'start': None, 'stop': None},
    {'court': 'txed', 'start': None, 'stop': None},
    {'court': 'txnd', 'start': None, 'stop': None},
    {'court': 'txsd', 'start': None, 'stop': None},
    {'court': 'txwd', 'start': None, 'stop': None},
    {'court': 'cofc', 'start': None, 'stop': None},
    {'court': 'utd', 'start': None, 'stop': None},
    {'court': 'vtd', 'start': None, 'stop': None},
    {'court': 'vid', 'start': None, 'stop': None},
    {'court': 'vaed', 'start': None, 'stop': None},
    {'court': 'vawd', 'start': None, 'stop': None},
    {'court': 'waed', 'start': None, 'stop': None},
    {'court': 'wawd', 'start': None, 'stop': None},
    {'court': 'wvnd', 'start': None, 'stop': None},
    {'court': 'wvsd', 'start': None, 'stop': None},
    {'court': 'wied', 'start': None, 'stop': None},
    {'court': 'wiwd', 'start': None, 'stop': None},
    {'court': 'wiwd', 'start': None, 'stop': None},
    {'court': 'wyd', 'start': None, 'stop': None},
    {'court': 'cit', 'start': None, 'stop': None},
    {'court': 'akb', 'start': None, 'stop': None},
    {'court': 'almb', 'start': None, 'stop': None},
    {'court': 'alnb', 'start': None, 'stop': None},
    {'court': 'alsb', 'start': None, 'stop': None},
    {'court': 'areb', 'start': None, 'stop': None},
    {'court': 'arwb', 'start': None, 'stop': None},
    {'court': 'azb', 'start': None, 'stop': None},
    {'court': 'cacb', 'start': None, 'stop': None},
    {'court': 'caeb', 'start': None, 'stop': None},
    {'court': 'canb', 'start': None, 'stop': None},
    {'court': 'casb', 'start': None, 'stop': None},
    {'court': 'cob', 'start': None, 'stop': None},
    {'court': 'ctb', 'start': None, 'stop': None},
    {'court': 'dcb', 'start': None, 'stop': None},
    {'court': 'deb', 'start': None, 'stop': None},
    {'court': 'flmb', 'start': None, 'stop': None},
    {'court': 'flnb', 'start': None, 'stop': None},
    {'court': 'flsb', 'start': None, 'stop': None},
    {'court': 'gamb', 'start': None, 'stop': None},
    {'court': 'ganb', 'start': None, 'stop': None},
    {'court': 'gasb', 'start': None, 'stop': None},
    {'court': 'gub', 'start': None, 'stop': None},
    {'court': 'hib', 'start': None, 'stop': None},
    {'court': 'ianb', 'start': None, 'stop': None},
    {'court': 'iasb', 'start': None, 'stop': None},
    {'court': 'idb', 'start': None, 'stop': None},
    {'court': 'ilcb', 'start': None, 'stop': None},
    {'court': 'ilnb', 'start': None, 'stop': None},
    {'court': 'ilsb', 'start': None, 'stop': None},
    {'court': 'innb', 'start': None, 'stop': None},
    {'court': 'insb', 'start': None, 'stop': None},
    {'court': 'ksb', 'start': None, 'stop': None},
    {'court': 'kyeb', 'start': None, 'stop': None},
    {'court': 'kywb', 'start': None, 'stop': None},
    {'court': 'laeb', 'start': None, 'stop': None},
    {'court': 'lamb', 'start': None, 'stop': None},
    {'court': 'lawb', 'start': None, 'stop': None},
    {'court': 'mab', 'start': None, 'stop': None},
    {'court': 'mdb', 'start': None, 'stop': None},
    {'court': 'meb', 'start': None, 'stop': None},
    {'court': 'mieb', 'start': None, 'stop': None},
    {'court': 'miwb', 'start': None, 'stop': None},
    {'court': 'mnb', 'start': None, 'stop': None},
    {'court': 'moeb', 'start': None, 'stop': None},
    {'court': 'mowb', 'start': None, 'stop': None},
    {'court': 'msnb', 'start': None, 'stop': None},
    {'court': 'mssb', 'start': None, 'stop': None},
    {'court': 'mtb', 'start': None, 'stop': None},
    {'court': 'nceb', 'start': None, 'stop': None},
    {'court': 'ncmb', 'start': None, 'stop': None},
    {'court': 'ncwb', 'start': None, 'stop': None},
    {'court': 'ndb', 'start': None, 'stop': None},
    {'court': 'neb', 'start': None, 'stop': None},
    {'court': 'nhb', 'start': None, 'stop': None},
    {'court': 'njb', 'start': None, 'stop': None},
    {'court': 'nmb', 'start': None, 'stop': None},
    {'court': 'nvb', 'start': None, 'stop': None},
    {'court': 'nyeb', 'start': None, 'stop': None},
    {'court': 'nynb', 'start': None, 'stop': None},
    {'court': 'nysb', 'start': None, 'stop': None},
    {'court': 'nywb', 'start': None, 'stop': None},
    {'court': 'ohnb', 'start': None, 'stop': None},
    {'court': 'ohsb', 'start': None, 'stop': None},
    {'court': 'okeb', 'start': None, 'stop': None},
    {'court': 'oknb', 'start': None, 'stop': None},
    {'court': 'okwb', 'start': None, 'stop': None},
    {'court': 'orb', 'start': None, 'stop': None},
    {'court': 'paeb', 'start': None, 'stop': None},
    {'court': 'pamb', 'start': None, 'stop': None},
    {'court': 'pawb', 'start': None, 'stop': None},
    {'court': 'prb', 'start': None, 'stop': None},
    {'court': 'rib', 'start': None, 'stop': None},
    {'court': 'scb', 'start': None, 'stop': None},
    {'court': 'sdb', 'start': None, 'stop': None},
    {'court': 'tneb', 'start': None, 'stop': None},
    {'court': 'tnmb', 'start': None, 'stop': None},
    {'court': 'tnwb', 'start': None, 'stop': None},
    {'court': 'txeb', 'start': None, 'stop': None},
    {'court': 'txnb', 'start': None, 'stop': None},
    {'court': 'txsb', 'start': None, 'stop': None},
    {'court': 'txwb', 'start': None, 'stop': None},
    {'court': 'utb', 'start': None, 'stop': None},
    {'court': 'vaeb', 'start': None, 'stop': None},
    {'court': 'vawb', 'start': None, 'stop': None},
    {'court': 'vib', 'start': None, 'stop': None},
    {'court': 'vtb', 'start': None, 'stop': None},
    {'court': 'waeb', 'start': None, 'stop': None},
    {'court': 'wawb', 'start': None, 'stop': None},
    {'court': 'wieb', 'start': None, 'stop': None},
    {'court': 'wiwb', 'start': None, 'stop': None},
    {'court': 'wvnb', 'start': None, 'stop': None},
    {'court': 'wvsb', 'start': None, 'stop': None},
    {'court': 'wyb', 'start': None, 'stop': None},
    {'court': 'nysb-mega', 'start': None, 'stop': None}
]


def date_yielder(start, stop):
    """
    Iterate over the dates, yielding them one at a time. Note that dates *decrement*, not increment, so start should
    be the high date, and stop is the low date.

    Eliminate Saturday and Sunday.
    """
    d = start + timedelta(days=1)
    while d >= stop:
        d -= timedelta(days=1)
        if d.weekday() in [5, 6]:
            continue
        yield d


def iterate_starters(starters):
    """
    Iterate over the starter dicts, hitting the run_downloader function once per date per court.
    """
    for starter in starters:
        for d in date_yielder(starter['start'], starter['stop']):
            run_downloader([starter['court']], start_date=d, end_date=d)


def __main__():
    iterate_starters(starters)
